apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost
spec:
  ports:
    - port: 2368
      targetPort: 2368
  selector:
    app: ghost
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost:5-alpine
        name: ghost
        env:
        - name: url
          value: http://ghost.haifa.work # e this is myr actual domain 
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: mysql # This matches the name of the MySQL service we made earlier
        - name: database__connection__user
          value: root
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        
        - name: database__connection__database
          value: ghost
        ports:
        - containerPort: 2368
          name: ghost
