apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: ghost
spec:
  encryptedData:
    password: AgA0MmFqPXPqLhS8mnEKkf2wUCdEBGKbY+Htpw0P/FWPtkKVKCi4b8/j4kX55IrIMcWY0zoLcWCGG8GtjEP579UZ93JsSDBbQVXqZ/n47dFtclA9UWVFnyGihrLUOhyOkt8t88cFmVfD6kDHNe2tUPSsVN0S82UZ13bf65wnE0vSl/5MHunDfqP/2q0/m0U+bLkhdcD/00FAcKvCDF/yOrG76JfnDckENCYnVDJMo0RWTNxANuO8q0gimiRP3NsIXdjxL6A4qNCDE+rpUUajR6GE5qDJVzmbyIRxZvZkrnfw9ha6UKTN9Qeab7xCO0Jm+8iAB9sd3hwFGnAK6gDFEKmNPy4SPBjg3Wb7QFGOK0kvk7wA0FFT4XNQHryXU9L0svvgGqKRAT8SKcbHtW8vyStMkfBtv3xID+p8vycJCIHx6v2kZ2mHrh0uvTMFXVBNZTmM5QWq3ePCG8YLWcKZABxrJ9dBbrU3dZTe+dqSQyIXUCFHkudk9Ah/BukrMvPdwwywDsR5SCg6m6Ddxku5K3g64ajeirGsJ8njwUpGZC6ZMWLYmbOARMbzd3JFxyeyKIhm/vNPX1w67c6jgJamkxNkeX+EG/OpsJNnhWzw8whh4i98mPgjhjMY67Oyl8TF433ijwx384J2uztwM6I4shCXZCR6tCHT2BqP1RdX/uoVePraE0d9V8cHsabLLsu09I57HOAXsLIvPA==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: ghost

