apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: ghost
spec:
  encryptedData:
    password: AgBhVujqKVJa03AdX6FiEYGuBnEk2eJ6NYRif/BAV9EOfVQEvlhqsBoWe3nEMVYS5EDWAkysJ8pCRoE92M0ZsWoSflUPqLjN6qY+hbNtEOuAblBUNHT3ydq2Ey6ORx1chTf+I4nmc63W32WqGAranlgGjrAW/abBezDnDIa0FNuBWWGAAxZrinNizMAIHi9ASVu+5VsVrltlE6Vju/KW8yxMo8YvjKXfYcF1U4nCcs6+h3gx++7OJml3vMXEUoGTEbhTnsMenhjkevEk7llOPFNnyCAdsq33oju2frARbm32lkjZLZ6dCisU7eQxx/y5b45OBlW3X7D+RUKpVgvH5RNt0ULN8Ej8av/uXA8yS0YMm66dhY90Nsj4pmj76vcm6upJEYRr5vonMSMvsptjCLeryhIOvYKM+exr+/wuUZ/5wbPuLPAdP4XwW6bwJUSqpsY177xZ8hBcno/liV4XvGJWA+1neEusJlctKqY57tJnyQ/oguSf/K7jxMz54TzFGnQhR/NLQyZmohTKWEfGI1FSfuJsxBQ8GRTgbSh9UHg1ZItHEXxQ9QRemAeJ+BBvJ59rEjIpJ0aSDX8HNGgoxd6F/cppV6372usnqXsLJ+YBEK+w81+FgJ/mTpf27VzYmMWXpzKnWvuAhamsdnUs0+Uq1D7pOEmjZKc2Xb97SjyX5H+fEubO85QEHZIYAD55KHnjb889OBC3wg==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: ghost

