apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: ghost
spec:
  encryptedData:
    password: AgBJ1CEbEgQcLjTbNCkLnPpQO2tGN4mMk86GNYSM6bdBKyuyEUBJuMtnoEKYmrMCNb5tUZKE5av9tndlACYGWzETp8GZn1YFjNP9uucP3EMcSBTDWuVCDu1SnoB8nKpe6AeG0iSNDhAv/p7CDqF0Nz08daq+QVYFmueyx69q7PYGew9NDWfFNHJR/cQ13Z1iLeSdTUGA2eKB0bMvY/5y9KtRCeKYJ8cuGQFgD/kcqIVuWCaLJKsCbQST6iC6YTdfz8PUhV4tyMQRnrsAF4KDtF/ui0LoaywxVYjBEo74CzEiiB8rmqOTvreQZpZd6Gy1c8K3CePw8xCgcQ9J+6bcuAKPt+2zUntOIxhI08ZHnByANe4kN29WN3txNLgACCA+HD7KOP7eqHZ+1BSLBeXD70NCQBLQKaW4tLkLgiJJfXzNvwU9NPYJ7I73dG6+/JpvoM/YjKstIh2tYgvxsEleDsXXUEmu/+f71Yb9hrTFF+u16dBiWd6J6c6GXS3h6CD1gdPcmXk9ZcdGRGYWR5aHKfd0g891FR2OFvWCyVNWAEL4riCKXg6fBivAULF57L9OUegPAbhckFcwrYO6VksnSRZt6UJhxD1+qL5lGrQBtHo7wtSMyB4RiBQboAgaV6cm29nuFGxsSiMb9wRBIMZLrJhCK0W/bQhv5waH4T3qizL/OGTI7lsTsHVJIw1f0Z1wfmi+9Qinf3LBoY42VuE=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: ghost

